name: kareem_tarek
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  drift: ^2.23.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  get_it: ^8.0.3
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.26

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.23.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  android: true
  ios: true
  color: "#5F33E1"
  image: Assets/images/app_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "Assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - Assets/images/
  fonts:
    - family: DM Sans
      fonts:
        - asset: Assets/fonts/DMSans-Regular.ttf
        - asset: Assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: Assets/fonts/DMSans-Bold.ttf
          weight: 700
